services:
  - type: web
    name: portfolio-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist

  - type: web
    name: portfolio-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
